services:
  webapplication-demo:
    image: ${DOCKER_REGISTRY-}webapplicationdemo
    build:
      context: .
      dockerfile: WebApplication-demo/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080